### ISSUE TITLE
Error when I used pytorch to run

### ISSUE THREAD

**Issue by michelleqyhqyh** [NVIDIA/FasterTransformer#176] opened 2021-12-31 06:53 UTC
python pytorch/decoder_sample.py 8 6 32 8 64 --time 
![image](https://user-images.githubusercontent.com/45490378/147808417-009fd05d-a53c-455b-b899-c8f013bea443.png)

**Comment by byshiue** [comment] 2021-12-31 07:14
Please describe the hardward, environment, docker, branch and building scripts you use, thanks.

**Comment by michelleqyhqyh** [comment] 2021-12-31 07:22
> Please describe the hardward, environment, docker, branch and building scripts you use, thanks.

I compile it in my local sever,. So I didn't used docker. My system is CENTOS7. My GPU is V100.
1. I downloaded the git
2. cmake -DSM=70 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON ..
3. make 
4. pip install transformers==2.5.1
5. ./bin/encoder_gemm 32 32 12 64 0 0
6. python pytorch/encoder_sample.py 32 12 32 12 64 --time
 
And the error is from step 6.

**Comment by byshiue** [comment] 2021-12-31 08:19
It seems that there are some issues for the fused mha initialization. Please try to use the v5.0_beta branch.

**Comment by michelleqyhqyh** [comment] 2021-12-31 08:50
> It seems that there are some issues for the fused mha initialization. Please try to use the v5.0_beta bran

I compiled dev_v5.0_beta, there is no the docment pytorch/  and file ./bin/encoder_gemm to generate.
How can I use with the dev_v5.0_beta branch?

**Comment by michelleqyhqyh** [comment] 2021-12-31 09:20
Besides, what does 'sm' mean?
![image](https://user-images.githubusercontent.com/45490378/147814814-f596c03a-1b98-4ee0-a435-b1e3d8841cd3.png)

**Comment by byshiue** [comment] 2021-12-31 10:15
SM is the compute capacity of GPU. The SM of V100 is 70. You can find the SM of other GPUs on NVIDIA official website.

**Comment by JeremyZhao1998** [comment] 2022-03-11 10:18
@michelleqyhqyh @byshiue  Hi, I'm also running this file without using docker. I'm facing another error:
![1646993799(1)](https://user-images.githubusercontent.com/41135963/157847971-3bbdae15-98e5-463a-a53a-9da09665f056.png)
It seems like error occurred in loading op. Have you met such error?

**Comment by byshiue** [comment] 2022-08-16 03:24
This bug is fixed in latest release. It is caused by CUDA_API version.

**Comment by byshiue** [comment] 2022-09-06 01:32
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.

**Closed by byshiue** 2022-09-06 01:32 UTC
