### ISSUE TITLE
bert batch 1 seq_len 64 head_num 8 layers 6 half  has segmentation fault(core dumped)

### ISSUE THREAD

**Issue by fangxiangyu** [NVIDIA/FasterTransformer#397] opened 2022-12-15 06:34 UTC
### Branch/Tag/Commit

v5.2

### Docker Image Version

nvcr.io/nvidia/tensorflow:22.04-tf1-py3

### GPU name

A10

### CUDA Driver

11.8

### Reproduced Steps

```shell
1、nvidia-docker run -ti --shm-size 5g --rm nvcr.io/nvidia/tensorflow:22.09-tf1-py3 bash
2、git clone https://github.com/NVIDIA/FasterTransformer.git
3、mkdir -p FasterTransformer/build
4、cd FasterTransformer/build
5、cmake -DSM=xx -DCMAKE_BUILD_TYPE=Release .. （ build cpp）
6、make -j12
7、./bin/bert_example
8、./bin/bert_example 1 6 64 8 64 1 0
```

**Comment by byshiue** [comment] 2022-12-16 15:11
The issue is fixed in https://github.com/NVIDIA/FasterTransformer/commit/83776ae7fefaabaf4fc75063d2a704fbeb84f2be, can you try the latest codes of main branch again?

**Comment by fangxiangyu** [comment] 2022-12-21 13:21
ok，thanks。

**Closed** 2022-12-21 13:21 UTC
Labels: bug
